- hosts: all
  become: yes
  vars:
    nginx_vhosts:
      - listen: "443 ssl http2"
        server_name: "{{hostname}}"
        root: "/var/www/{{hostname}}"
        index: "index.php index.html index.htm"
        state: "present"
        filename: "{{hostname}}.conf"
        nginx_remove_default_vhost: true
        extra_parameters: |
          ssl_certificate     /etc/ssl/certs/ssl-cert-{{hostname}}.pem;
          ssl_certificate_key /etc/ssl/private/ssl-cert-{{hostname}}.key;
          ssl_protocols       TLSv1.2;
          ssl_ciphers         HIGH:!aNULL:!MD5;

  tasks:
    - name: Upload SSL certificate files
      ansible.builtin.copy:
        src: "{{cert_path}}"
        dest: "/etc/ssl/certs/ssl-cert-{{hostname}}.pem"

    - name: Upload SSL certificate key files
      ansible.builtin.copy:
        src: "{{private_key_path}}"
        dest: "/etc/ssl/private/ssl-cert-{{hostname}}.key"
        
    - name: Install Nginx
      include_role:
        name: geerlingguy.nginx

    - name: Ensure site home directory exists.
      file:
        path: "/var/www/{{hostname}}"
        state: directory
        mode: 0755

    - name: Upload a welcome page
      ansible.builtin.template:
        src: ./template/welcome.html.j2
        dest: "/var/www/{{hostname}}/index.html"

    - name: allow https port in the server
      ansible.builtin.command: ufw allow https